config/routes.rb
Rails.application.routes.draw do
  resources :games do
    member do
      post :leave
      post :run_round
      post :start_now
      post :start_with_bots
      post :update_level
    end
  end
  delete 'sessions/destroy'
  get 'leader_boards', to: 'games#leader_boards'
  root 'sessions#new'
  post 'sessions/create'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :game_users
  has_many :users, through: :game_users
  scope :pending, -> { where(start_at: nil) }
  scope :in_progress, -> { where.not(start_at: nil).where(finish_at: nil) }
  scope :finished, -> { where.not(start_at: nil).where.not(finish_at: nil) }

  serialize :go_fish_game, GoFishGame

  def start
    player_names = ordered_users.map { |u| u.name }
    go_fish_game = GoFishGame.new(level: level, player_names: player_names, player_num: player_num)
    update(go_fish_game: go_fish_game, start_at: Time.zone.now)
  end

  def ordered_users
    users.includes(:game_users).sort_by{|user| user.game_users.detect{|game_user| game_user.game_id == id}.created_at}
  end

  def pending
    start_at == nil
  end

  def in_progress
    start_at != nil && finish_at == nil
  end

  def finished
    start_at != nil && finish_at != nil
  end

  def change_level
    if go_fish_game.level == 'hard'
      go_fish_game.set_level('easy')
    else
      go_fish_game.set_level('hard')
    end
    update(go_fish_game: go_fish_game)
  end

  def result leader_board: {wins: 0, ties: 0, losses: 0}, name:
    result = go_fish_game.winners.map.with_index do |player, index|
      user = User.find_by(name: player.name)
      if user && user.name == name
        if index == 0 && go_fish_game.winners[1].points != player.points
          leader_board[:wins] += 1
        elsif go_fish_game.winners[0].points == player.points
          leader_board[:ties] += 1
        else
          leader_board[:losses] += 1
        end
        leader_board
      else
        ''
      end
    end.flatten
    result.select{|r| r != ''}
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include SessionsHelper
  skip_before_action :verify_authenticity_token
  before_action :redirect_home?

  def leader_boards
    @game_users = GameUser.all
    @results = User.all.map do |user|
      games = Game.finished.select {|g| g.users.include?(user)}
      leader_board = {wins: 0, ties: 0, losses: 0, games_played: games.count}
      games.map do |game|
        game.result(leader_board: leader_board, name: user.name)
      end
      {name: user.name, leader_board: leader_board}
    end
  end

  def show
    @game = Game.find(params[:id])
    @user = current_user
    unless @game.users.include?(@user) || @user == nil
      join_game @game
      pusher_client.trigger("app", "another-joined", {game_id: @game.id, user_id: "#{@user.id}"})
    end
    if @game.users.length == @game.player_num && @game.start_at == nil
      @game.start
      pusher_client.trigger("app", "game-is-starting", {game_id: @game.id, user_id: "#{@user.id}"})
    end
    if @game.go_fish_game != nil && @game.go_fish_game.winners != false && @game.finish_at == nil
      @game.update(finish_at: Time.zone.now)
      pusher_client.trigger("Game#{@game.id}", "game-has-changed", {message: 'The game is ended'})
    end
    respond_to do |format|
      format.html
      format.json { render json: {game: @game.go_fish_game.players_json(@user.name)} }
    end
  end

  def start_with_bots
    @game = Game.find(params[:id])
    @game.start
    pusher_client.trigger("app", "game-is-starting", {game_id: @game.id, user_id: "#{current_user.id}"})
    redirect_to @game
  end

  def start_now
    @game = Game.find(params[:id])
    if @game.users.length > 1
      @game.update player_num: @game.users.length
      @game.start
      pusher_client.trigger("app", "game-is-starting", {game_id: @game.id, user_id: "#{current_user.id}"})
      redirect_to @game
    else
      redirect_to @game, notice: ["You can't play gofish by your self"]
    end
  end

  def leave
    game = Game.find(params[:id])
    game.game_users.find_by(user: current_user).destroy
    game.destroy if game.users.none?
    pusher_client.trigger("app", "someone-left", {game_id: game.id, user_id: "#{current_user.id}"})
    redirect_to games_path
  end

  def index
    @user = current_user
    @in_progress = Game.in_progress.select {|g| g.users.include?(@user)}
    @finished = Game.finished.select {|g| g.users.include?(@user)}
    @pending_games = Game.pending
  end

  def create
    @game = Game.new(create_game_params)
    if @game.save
      pusher_client.trigger("app", "new-games", {game_id: @game.id, user_id: "#{current_user.id}"})
      redirect_to @game
    end
  end

  def new
    @game = Game.new
  end

  def update_level
    @game = Game.find(params[:id])
    @game.change_level
    pusher_client.trigger("Game#{@game.id}", "game-has-changed", {message: 'Update level'})
  end

  def run_round
    @game = Game.find(params[:id])
    player = @game.go_fish_game.players_find_by(name: current_user.name)
    target = @game.go_fish_game.players_find_by(name: params['target_player'])
    result = @game.go_fish_game.run_turn(fisher: player, target: target, rank: params['target_card'])
    @game.save
    pusher_client.trigger("Game#{@game.id}", "game-has-changed", {message: 'Round has been run'})
  end

  private

  def join_game game
    @game_user = GameUser.create(game_id: game.id, user_id: @user.id)
  end

  def create_game_params
    params.require(:game).permit([:level, :player_num])
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_end_game.slim
h1 The Game is over
-winners = @game.go_fish_game.winners.select {|pl| pl.points == @game.go_fish_game.winners[0].points}
-others = @game.go_fish_game.winners.select {|pl| pl.points != @game.go_fish_game.winners[0].points}
-if winners.length == 1
  h3 = "#{winners.first.name} won with #{winners.first.points} points"
-else
  h3 = "#{winners.map(&:name).join(', ')} tied with #{winners.first.points} points"
-others.each do |player|
  h3 = "#{player.name} had #{player.points} point(s)"
div.flex-log
  div.end_game_log
    h2.book Game logs
    - @game.go_fish_game.logs.reverse.each do |log|
      h4.book = log.to_player_json

app/views/games/index.html.slim
h2 Pending Games
-if @pending_games.any?
  - @pending_games.each do |game|
    h4 = "Players: #{game.ordered_users.map(&:name).join(', ')}"
    h3 = link_to "Waiting for #{game.player_num - game.ordered_users.length} of #{game.player_num} players", game, class: 'link'
- else
  h3 No games are created yet create one

h2 In Progress
-if @in_progress.any?
  - @in_progress.each do |game|
    h3 = link_to "#{game.ordered_users.map(&:name).join(', ')}", game, class: 'link'
- else
  h3 No games are in progress, join or create one

h2 Finished
-if @finished.any?
  - @finished.each do |game|
    h3 = link_to "#{game.ordered_users.map(&:name).join(', ')}", game, class: 'link'
- else
  h3 You have not finished any games, finish a game to see the log

app/views/games/leader_boards.html.slim
-if @results.any?
  h1 Leader Board
  .flex-wrapper
    - @results.each do |result|
      .leader-board
        -hash = result[:leader_board]
        h3 = result[:name]
        h4 = "Wins: #{hash[:wins]}"
        h4 = "Ties: #{hash[:ties]}"
        h4 = "Losses: #{hash[:losses]}"
        h4 = "Games Played: #{hash[:games_played]}"
-else
  h1 No Leader Boards

app/views/games/new.html.slim
h1 How many players do you want to play with?
= form_for @game, url: games_url, method: "post" do |f|
  = f.hidden_field :level, value: 'hard'
  / = f.select :level, ['easy', 'hard']
  = f.label 'Number of Player: ', class: 'label'
  = f.number_field :player_num, min: 2 ,max: 8, value: 4
  = f.hidden_field :go_fish_game
  = f.submit class: 'button', value: 'Create'

app/views/games/show.html.slim
- if @game.pending == true
  -if notice
    h1 = notice.join ', '
  h1 = "There are #{@game.ordered_users.length} of #{@game.player_num} to start the game"
  - @game.ordered_users.each do |user|
    h1 = user.name
  - if @game.ordered_users.first == @user
    h3 = link_to 'Start Now With Bots', start_with_bots_game_path(@game), method: :post, class: 'link'
    h3 = link_to 'Start Now', start_now_game_path(@game), method: :post, class: 'link'
  h3 = link_to 'leave', leave_game_path(@game), method: :post, class: 'link'
-elsif @game.in_progress == true || @game.finished == true
  = react_component('GameView', { game_id: @game.id})